viewallproduct and homepage
thdailong/course-PRN231 pull request #6
Opened 2023-10-17 03:33 UTC by buitannguyen2612

check pls, some lib have classname can not use module.css

2023-10-17 03:52 UTC, thdailong requested changes
Please format your code before commiting!
You can use prettier

2023-10-17 03:52 UTC, thdailong commented on package.json
> +    "react-paginate": "^8.2.0"
Isn't we already have MUI pagination?

2023-10-17 03:52 UTC, thdailong commented on app/ViewAllProduct/AllProduct/pages/until.js
What is until.js??

2023-10-17 04:04 UTC, buitannguyen2612 commented on package.json
> +    "react-paginate": "^8.2.0"
fixed

2023-10-17 04:04 UTC, buitannguyen2612 commented on app/ViewAllProduct/AllProduct/pages/until.js
fixed

2023-10-19 13:38 UTC, thdailong approved these changes

2023-10-19 13:38 UTC, merged